# Generated by Django 4.0.6 on 2023-03-10 13:58

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('phone_number', models.IntegerField(blank=True, null=True)),
                ('User_id', models.IntegerField(primary_key=True, serialize=False)),
                ('profile_img', models.FileField(null=True, upload_to='Uploads/user/profile', validators=[user.models.User.validate_file_size])),
                ('is_order', models.BooleanField(default=None)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='add_product',
            name='Product_img',
            field=models.FileField(null=True, upload_to='Uploads/user/profile'),
        ),
    ]
