# Generated by Django 4.0.6 on 2023-03-10 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_remove_order_product_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_product',
            name='product_price',
            field=models.FloatField(null=True),
        ),
    ]
